apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: gw-to-secret
  namespace: user01
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: gateway-ns
  to:
  - group: ""
    kind: Secret
    name: certificate